[package]
name = "rle"
version = "0.0.0"
readme = "README.md"
license = "MIT"
keywords = ["run-length-encoding", "compression", "rle", "compression-algorithm"]
authors = ["Owez <root@ogriffiths.com>"]
edition = "2018"
